# Generated by Django 5.2.5 on 2025-08-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chathistory_name_alter_chathistory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
