# Generated by Django 5.2.5 on 2025-09-19 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chathistory_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='chathistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.chathistory'),
        ),
    ]
